### ISSUE TITLE
Objects not parsed correctly

### ISSUE THREAD

**Issue by KumaVolt** [saleem-hadad/larecipe-swagger#1]
Found this bug when adding default-params

[![Screenshot from Gyazo](https://gyazo.com/4063fff35297496739a146d4aac776f1/raw)](https://gyazo.com/4063fff35297496739a146d4aac776f1)

**Comment by scsddeputy** [comment]
are you defining the parameters as `:default-params={'foo': 'bar'}`? note the : before the default

**Comment by KumaVolt** [comment]
Sorry for the late answer.
@scsddeputy , your answer is correct thank you!
I have been switching frameworks alot lately, so forgot about that.
